---
- name: Playbook to upload Red Hat Discovery reports to Red Hat Insights
  hosts: local
  gather_facts: false
  vars:
    dsc_server: <your dsc ip address>
    dsc_port: 9443
    dsc_username: <your dsc username>
    dsc_password: <your dsc password>
  tasks:
  - name: Ensure discovery-cli and tmux are installed
    package:
      name: 
        - discovery-cli
        - tmux
      state: present
    become: true

  - name: Create missing config file
    ansible.builtin.file:
      path: "/home/{{ lookup('env','USER') }}/.config/qpc/server.config"

  - name: Configure Discovery server
    command: dsc server config --host "{{ dsc_server }}" --port "{{ dsc_port }}"

  - name: Login to Discovery server
    command: dsc server login --username "{{ dsc_username }}" --password "{{ dsc_password }}"

  - name: Get list of existing scans
    command: dsc scan list
    register: scans

  - name: Get list of scan reports
    set_fact:
      parsed_scans: "{{ scans.stdout_lines | join('') | from_json }}"

  - name: Get list of completed scan reports
    set_fact:
      completed_scans: "{{ parsed_scans | selectattr('most_recent.status', 'equalto', 'completed') | list }}"

  - name: Get list of report_ids
    set_fact:
      report_ids: "{{ completed_scans | map(attribute='jobs') | flatten | selectattr('report_id', 'defined') | map(attribute='report_id') | list }}"

  - name: Remove existing tmux session
    command: tmux kill-session -t insights-login
    ignore_errors: yes

  - name: Start tmux to login to Insights
    command: tmux new-session -d -s insights-login 'dsc insights login'

  - name: Pause 1 sec (give tmux and dsc the time to start)
    pause:
      seconds: 1

  - name: Capture pane
    command: /usr/bin/tmux capture-pane

  - name: Save buffer
    command: /usr/bin/tmux show-buffer
    register: login_output

  - name: Display authorization instructions
    debug: msg="{{ login_output.stdout_lines }}"

  - name: Complete instructions and press ENTER
    pause:
      prompt: Please visit the Authorization URL above to grant access to dsc. Then press ENTER to continue.

  - name: Pause 1 sec (give dsc the time to get the Authorization token)
    pause:
      seconds: 1

  - name: Upload reports to Insights
    command: dsc insights publish --report {{ item }}
    with_items: "{{ report_ids }}"
